# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 CommonHuman-Lab
"""WAF signature data: fingerprints and recommended evasion strategies.

This module contains ONLY data (WafSignature dataclass + SIGNATURES list).
The detection logic (HTTP probing, scoring) lives in each tool's own
waf_detect.py so it can use the tool's Injector instance.

Evasion lists per signature contain both XSS-specific and SQLi-specific
strategy names. Each tool filters to the strategies it implements.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Tuple

from .payloads import (
    _CLOUDFLARE, _AKAMAI, _IMPERVA, _AWS_WAF, _MODSECURITY,
    _SUCURI, _F5_BIGIP, _BARRACUDA, _WORDFENCE, _FORTIWEB,
)
from ..encoders.transforms import (
    EVASION_CASE_MIXING, EVASION_CHUNKED_TAGS, EVASION_COMMENT_BREAK,
    EVASION_DOUBLE_ENCODE, EVASION_HTML_ENCODE, EVASION_NEWLINE,
    EVASION_NULL_BYTE, EVASION_UNICODE,
    EVASION_SQL_CASE, EVASION_SQL_COMMENT, EVASION_SQL_ENCODE,
    EVASION_SQL_MULTILINE, EVASION_SQL_WHITESPACE,
)


@dataclass
class WafSignature:
    name:           str
    header_clues:   List[Tuple[str, str]] = field(default_factory=list)  # (header, regex)
    body_clues:     List[str]             = field(default_factory=list)  # body regexes
    status_codes:   List[int]             = field(default_factory=list)
    evasions:       List[str]             = field(default_factory=list)  # recommended order
    extra_payloads: List[str]             = field(default_factory=list)  # WAF-specific XSS payloads

# Scoring: header match +2, body match +1, status code match +1.
# Threshold: score >= 2 for a match; >= 4 for high confidence.
SIGNATURES: List[WafSignature] = [
    WafSignature(
        name="Cloudflare",
        header_clues=[
            ("server",           r"cloudflare"),
            ("cf-ray",           r".+"),
            ("cf-cache-status",  r".+"),
        ],
        body_clues=[r"cloudflare", r"cf-ray", r"Attention Required"],
        status_codes=[403, 503],
        evasions=[
            EVASION_SQL_COMMENT, EVASION_SQL_CASE,
            EVASION_UNICODE, EVASION_CASE_MIXING, EVASION_COMMENT_BREAK, EVASION_NEWLINE,
        ],
        extra_payloads=_CLOUDFLARE,
    ),
    WafSignature(
        name="Akamai",
        header_clues=[
            ("server",            r"AkamaiGHost"),
            ("x-check-cacheable", r".+"),
        ],
        body_clues=[r"Access Denied", r"Reference #\d+\.\w+"],
        status_codes=[403],
        evasions=[
            EVASION_SQL_WHITESPACE, EVASION_SQL_COMMENT,
            EVASION_HTML_ENCODE, EVASION_DOUBLE_ENCODE, EVASION_CHUNKED_TAGS,
        ],
        extra_payloads=_AKAMAI,
    ),
    WafSignature(
        name="Imperva",
        header_clues=[
            ("x-iinfo", r".+"),
            ("x-cdn",   r"Imperva"),
        ],
        body_clues=[r"Incapsula incident", r"incapsula", r"Request unsuccessful"],
        status_codes=[403],
        evasions=[
            EVASION_SQL_ENCODE,
            EVASION_UNICODE, EVASION_NULL_BYTE, EVASION_CASE_MIXING,
        ],
        extra_payloads=_IMPERVA,
    ),
    WafSignature(
        name="AWS WAF",
        header_clues=[
            ("x-amzn-requestid", r".+"),
            ("x-amz-cf-id",      r".+"),
        ],
        body_clues=[r"AWS WAF", r"Request blocked"],
        status_codes=[403],
        evasions=[
            EVASION_SQL_COMMENT, EVASION_SQL_CASE,
            EVASION_HTML_ENCODE, EVASION_CASE_MIXING, EVASION_UNICODE,
        ],
        extra_payloads=_AWS_WAF,
    ),
    WafSignature(
        name="ModSecurity",
        header_clues=[("server", r"mod_security")],
        body_clues=[
            r"ModSecurity",
            r"Not Acceptable!",
            r"406 Not Acceptable",
            r"This error was generated by Mod_Security",
        ],
        status_codes=[406, 403, 501],
        evasions=[
            EVASION_SQL_MULTILINE, EVASION_SQL_CASE,
            EVASION_CASE_MIXING, EVASION_COMMENT_BREAK, EVASION_CHUNKED_TAGS, EVASION_NULL_BYTE,
        ],
        extra_payloads=_MODSECURITY,
    ),
    WafSignature(
        name="Sucuri",
        header_clues=[
            ("x-sucuri-id",    r".+"),
            ("x-sucuri-cache", r".+"),
            ("server",         r"Sucuri"),
        ],
        body_clues=[r"Sucuri WebSite Firewall", r"sucuri.net", r"Access Denied - Sucuri"],
        status_codes=[403],
        evasions=[
            EVASION_SQL_ENCODE,
            EVASION_UNICODE, EVASION_DOUBLE_ENCODE,
        ],
        extra_payloads=_SUCURI,
    ),
    WafSignature(
        name="F5 BIG-IP ASM",
        header_clues=[
            ("x-cnection",  r".+"),
            ("set-cookie",  r"TS[0-9a-f]{8}"),
        ],
        body_clues=[r"The requested URL was rejected", r"F5 Networks"],
        status_codes=[403],
        evasions=[
            EVASION_SQL_WHITESPACE, EVASION_SQL_COMMENT,
            EVASION_CHUNKED_TAGS, EVASION_NEWLINE, EVASION_CASE_MIXING,
        ],
        extra_payloads=_F5_BIGIP,
    ),
    WafSignature(
        name="Barracuda",
        header_clues=[("set-cookie", r"barra_counter_session")],
        body_clues=[r"Barracuda Web Application Firewall", r"barra_counter_session"],
        status_codes=[403],
        evasions=[
            EVASION_SQL_ENCODE,
            EVASION_HTML_ENCODE, EVASION_DOUBLE_ENCODE,
        ],
        extra_payloads=_BARRACUDA,
    ),
    WafSignature(
        name="Wordfence",
        header_clues=[],
        body_clues=[
            r"Wordfence",
            r"Generated by Wordfence",
            r"This response was generated by Wordfence",
        ],
        status_codes=[403],
        evasions=[
            EVASION_SQL_COMMENT,
            EVASION_UNICODE, EVASION_CASE_MIXING,
        ],
        extra_payloads=_WORDFENCE,
    ),
    WafSignature(
        name="Fortinet FortiWeb",
        header_clues=[("set-cookie", r"FORTIWAFSID")],
        body_clues=[r"FortiWeb", r"Application Firewall"],
        status_codes=[403],
        evasions=[
            EVASION_SQL_CASE, EVASION_SQL_COMMENT,
            EVASION_HTML_ENCODE, EVASION_CHUNKED_TAGS,
        ],
        extra_payloads=_FORTIWEB,
    ),
]

# Generic block signals — no specific WAF identified.
GENERIC_BLOCK_BODIES: List[str] = [
    r"Access Denied",
    r"Forbidden",
    r"Request Blocked",
    r"Security violation",
    r"Illegal request",
    r"Attack detected",
    # Inline WAF responses that return 200 OK with a block message in the body
    r"WAF:\s*BLOCKED",
    r"WAF caught",
]
